### ISSUE TITLE
History of transactions

### ISSUE THREAD

**Issue by ms-86** [Anchor-Protocol/anchor-notebooks#1]
Hi

Was wondering if by any chance would it be possible to get list of transactions for specified address.

**Comment by iamssen** [comment]
@ms-86 please refer this notebook <https://github.com/Anchor-Protocol/anchor-notebooks/blob/main/tx-history.ipynb>

**Comment by ms-86** [comment]
@iamssen Thanks for clarification but it seems that notebook is no longer available.

**Comment by iamssen** [comment]
@ms-86 file name is changed https://github.com/Anchor-Protocol/anchor-notebooks/blob/main/mypage_transaction_history.ipynb
